# -*- coding: utf-8 -*-
"""CIE Q3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O46hFdq1pQAjr1-S3iyIRwhTK-pLmdQO
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import seaborn as sns

iris = load_iris()
x = iris.data
y = iris.target
df = pd.DataFrame(data=x, columns=iris.feature_names)
df

df['species'] = pd.Categorical.from_codes(y, iris.target_names)
print(df.head())
print(df.describe())
print(df['species'].value_counts())

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)
clf =DecisionTreeClassifier(random_state=42)
clf.fit(x_train,y_train)
y_pred =clf.predict(x_test)
accuracy =accuracy_score(y_test, y_pred)
print(f'Accuracy of the Decision Tree model: {accuracy:.2f}')